module.exports = {
  disableEmoji: false,
  format: '{emoji}{type}{scope}: {subject}',
  list: [
    "Add",
    "Fix",
    "Ref",
    "Wip",
    "Del",
    "Perf",
    "UI",
    "Init",
    "Cfg",
    "Cln",
    "Typo",
    "Seo",
    "Pkg",
    "Ignore",
    "Merge",
    "Tag",
    "Sec",
    "Test",
    "Hot",
    "Remove",
    "Style",
    "Rename",
    "Move",
    "UX",
    "Doc",
    "Feat",
  ],
  maxMessageLength: 164,
  minMessageLength: 3,
  questions: ['type', 'scope', 'subject'],
  scopes: [],
  types: {
    Add:    {value: "Add",       emoji: "✨",  description: "Add",          },
    Fix:    {value: "Fix",       emoji: "🐛",  description: "Fix",          },
    Doc:    {value: "Doc",       emoji: "📚",  description: "Docs",         },
    Cln:    {value: "Cln",       emoji: "🧹",  description: "Cleaning",     },
    Wip:    {value: "Wip",       emoji: "🚧",  description: "WIP",          },
    Style:  {value: "Style",     emoji: "🎨",  description: "Style",        },
    UI:     {value: "UI",        emoji: "🎨",  description: "UI",           },
    Perf:   {value: "Perf",      emoji: "⚡",  description: "Perf",         },
    Ref:    {value: "Ref",       emoji: "♻️",  description: "Refactor",     },
    Feat:   {value: "Feat",      emoji: "✨",  description: "Feat",         },
    Del:    {value: "Del",       emoji: "🔥",  description: "Delete",        },
    Remove: {value: "Remove",    emoji: "🔥",  description: "Remove",       },
    Hot:    {value: "Hot",       emoji: "🚑",  description: "Hotfix",       },
    Test:   {value: "Test",      emoji: "✅",  description: "Test",         },
    Cfg:    {value: "Cfg",       emoji: "🔧",  description: "Config",       },
    Init:   {value: "Init",      emoji: "🎉",  description: "Init",         },
    Sec:    {value: "Sec",       emoji: "🔒",  description: "Security",     },
    Tag:    {value: "Tag",       emoji: "🔖",  description: "Release/Tag",  },
    Merge:  {value: "Merge",     emoji: "🔀",  description: "Branch Merge", },
    Rename: {value: "Rename",    emoji: "🚚",  description: "Rename",  },
    Move:   {value: "Move",      emoji: "🚚",  description: "Move",         },
    Ignore: {value: "Ignore",    emoji: "🙈",  description: "Gitignore",    },
    Pkg:    {value: "Pkg",       emoji: "📦",  description: "Package",      },
    Seo:    {value: "Seo",       emoji: "🔍",  description: "SEO",          },
    Typo:   {value: "Typo",      emoji: "✏️",  description: "Typo",         },
    UX:     {value: "UX",        emoji: "🚸",  description: "UX",           }
    // cln: { description: "🎨Cleaning", emoji: "🎨", value: "Cln" },
    // doc: { description: "📝Docs", emoji: "📝", value: "Doc" },
  }
};
